import turtle

tl = turtle.Turtle()
wn = turtle.Screen()

def fractal (garis, ukuran):
    if ukuran == 0:
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis/2)
        tl.left(90)
        tl.forward(garis)
        tl.right(90)
        tl.forward(garis/2)
        tl.right(90)
        tl.forward(garis/2)
        tl.right(90)
        tl.forward(garis)
        tl.right(90)
        tl.forward(garis/2)
        tl.right(90)
        tl.forward(garis/2)
    else:
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis)
        tl.left(90)
        tl.forward(garis/2)
        tl.left(90)
        tl.forward(garis)
        tl.right(90)
        tl.forward(garis/2)
        tl.right(90)
        tl.forward(garis/2)
        tl.right(90)
        tl.forward(garis)
        tl.right(180)
        fractal(garis/2, ukuran-1)

garis = int(input("Panjang garis = "))
jumlah = int(input("Jumlah Level = "))
fractal(garis, jumlah)
